//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IDomoService
{
    
    string[] GetHouses();
    
    string GetHouseDescription(int i);
    
    int Set(int RefDevice, int RefProperty, string Value);
    
    string Get(int RefDevice, int RefProperty);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetHouses", Namespace="http://DomoMobile.com")]
public partial class GetHousesRequest
{
    
    public GetHousesRequest()
    {
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetHousesResponse", Namespace="http://DomoMobile.com")]
public partial class GetHousesResponse
{
    
    [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Namespace="http://DomoMobile.com", Order=0)]
    [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
    public string[] GetHousesResult;
    
    public GetHousesResponse()
    {
    }
    
    public GetHousesResponse(string[] GetHousesResult)
    {
        this.GetHousesResult = GetHousesResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetHouseDescription", Namespace="http://DomoMobile.com")]
public partial class GetHouseDescriptionRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=0)]
    public int i;
    
    public GetHouseDescriptionRequest()
    {
    }
    
    public GetHouseDescriptionRequest(int i)
    {
        this.i = i;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetHouseDescriptionResponse", Namespace="http://DomoMobile.com")]
public partial class GetHouseDescriptionResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://DomoMobile.com", Order=0)]
    public string GetHouseDescriptionResult;
    
    public GetHouseDescriptionResponse()
    {
    }
    
    public GetHouseDescriptionResponse(string GetHouseDescriptionResult)
    {
        this.GetHouseDescriptionResult = GetHouseDescriptionResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="Set", Namespace="http://DomoMobile.com")]
public partial class SetRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=0)]
    public int RefDevice;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=1)]
    public int RefProperty;
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://DomoMobile.com", Order=2)]
    public string Value;
    
    public SetRequest()
    {
    }
    
    public SetRequest(int RefDevice, int RefProperty, string Value)
    {
        this.RefDevice = RefDevice;
        this.RefProperty = RefProperty;
        this.Value = Value;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="SetResponse", Namespace="http://DomoMobile.com")]
public partial class SetResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=0)]
    public int SetResult;
    
    public SetResponse()
    {
    }
    
    public SetResponse(int SetResult)
    {
        this.SetResult = SetResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="Get", Namespace="http://DomoMobile.com")]
public partial class GetRequest
{
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=0)]
    public int RefDevice;
    
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://DomoMobile.com", Order=1)]
    public int RefProperty;
    
    public GetRequest()
    {
    }
    
    public GetRequest(int RefDevice, int RefProperty)
    {
        this.RefDevice = RefDevice;
        this.RefProperty = RefProperty;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.Xml.Serialization.XmlRootAttribute(ElementName="GetResponse", Namespace="http://DomoMobile.com")]
public partial class GetResponse
{
    
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Namespace="http://DomoMobile.com", Order=0)]
    public string GetResult;
    
    public GetResponse()
    {
    }
    
    public GetResponse(string GetResult)
    {
        this.GetResult = GetResult;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class DomoServiceClient : Microsoft.Tools.ServiceModel.CFClientBase<IDomoService>, IDomoService
{
    
    public static System.ServiceModel.EndpointAddress EndpointAddress = new System.ServiceModel.EndpointAddress("http://localhost:8000/DomoService/DomoService");
    
    public DomoServiceClient() : 
            this(CreateDefaultBinding(), EndpointAddress)
    {
    }
    
    public DomoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
        addProtectionRequirements(binding);
    }
    
    private GetHousesResponse GetHouses(GetHousesRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://DomoMobile.com/IDomoService/GetHouses";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://DomoMobile.com/IDomoService/GetHousesResponse";
        info.ResponseIsWrapped = true;
        GetHousesResponse retVal = base.Invoke<GetHousesRequest, GetHousesResponse>(info, request);
        return retVal;
    }
    
    public string[] GetHouses()
    {
        GetHousesRequest request = new GetHousesRequest();
        GetHousesResponse response = this.GetHouses(request);
        return response.GetHousesResult;
    }
    
    private GetHouseDescriptionResponse GetHouseDescription(GetHouseDescriptionRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://DomoMobile.com/IDomoService/GetHouseDescription";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://DomoMobile.com/IDomoService/GetHouseDescriptionResponse";
        info.ResponseIsWrapped = true;
        GetHouseDescriptionResponse retVal = base.Invoke<GetHouseDescriptionRequest, GetHouseDescriptionResponse>(info, request);
        return retVal;
    }
    
    public string GetHouseDescription(int i)
    {
        GetHouseDescriptionRequest request = new GetHouseDescriptionRequest(i);
        GetHouseDescriptionResponse response = this.GetHouseDescription(request);
        return response.GetHouseDescriptionResult;
    }
    
    private SetResponse Set(SetRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://DomoMobile.com/IDomoService/Set";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://DomoMobile.com/IDomoService/SetResponse";
        info.ResponseIsWrapped = true;
        SetResponse retVal = base.Invoke<SetRequest, SetResponse>(info, request);
        return retVal;
    }
    
    public int Set(int RefDevice, int RefProperty, string Value)
    {
        SetRequest request = new SetRequest(RefDevice, RefProperty, Value);
        SetResponse response = this.Set(request);
        return response.SetResult;
    }
    
    private GetResponse Get(GetRequest request)
    {
        CFInvokeInfo info = new CFInvokeInfo();
        info.Action = "http://DomoMobile.com/IDomoService/Get";
        info.RequestIsWrapped = true;
        info.ReplyAction = "http://DomoMobile.com/IDomoService/GetResponse";
        info.ResponseIsWrapped = true;
        GetResponse retVal = base.Invoke<GetRequest, GetResponse>(info, request);
        return retVal;
    }
    
    public string Get(int RefDevice, int RefProperty)
    {
        GetRequest request = new GetRequest(RefDevice, RefProperty);
        GetResponse response = this.Get(request);
        return response.GetResult;
    }
    
    public static System.ServiceModel.Channels.Binding CreateDefaultBinding()
    {
        System.ServiceModel.Channels.CustomBinding binding = new System.ServiceModel.Channels.CustomBinding();
        binding.Elements.Add(new System.ServiceModel.Channels.TextMessageEncodingBindingElement(System.ServiceModel.Channels.MessageVersion.Soap11, System.Text.Encoding.UTF8));
        binding.Elements.Add(new System.ServiceModel.Channels.HttpTransportBindingElement());
        return binding;
    }
    
    private void addProtectionRequirements(System.ServiceModel.Channels.Binding binding)
    {
        if ((IsSecureMessageBinding(binding) == false))
        {
            return;
        }
        System.ServiceModel.Security.ChannelProtectionRequirements cpr = new System.ServiceModel.Security.ChannelProtectionRequirements();
        ApplyProtection("http://DomoMobile.com/IDomoService/GetHouses", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/GetHouses", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/GetHouseDescription", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/GetHouseDescription", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/Set", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/Set", cpr.IncomingEncryptionParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/Get", cpr.IncomingSignatureParts, true);
        ApplyProtection("http://DomoMobile.com/IDomoService/Get", cpr.IncomingEncryptionParts, true);
        if ((binding.MessageVersion.Addressing == System.ServiceModel.Channels.AddressingVersion.None))
        {
            ApplyProtection("*", cpr.OutgoingSignatureParts, true);
            ApplyProtection("*", cpr.OutgoingEncryptionParts, true);
        }
        else
        {
            ApplyProtection("http://DomoMobile.com/IDomoService/GetHousesResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/GetHousesResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/GetHouseDescriptionResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/GetHouseDescriptionResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/SetResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/SetResponse", cpr.OutgoingEncryptionParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/GetResponse", cpr.OutgoingSignatureParts, true);
            ApplyProtection("http://DomoMobile.com/IDomoService/GetResponse", cpr.OutgoingEncryptionParts, true);
        }
        this.Parameters.Add(cpr);
    }
}
